//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCClaimMedia
    {
        public int mediaID { get; set; }
        public int clientID { get; set; }
        public int claimID { get; set; }
        public int uploadedByPersonID { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string mediaType { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string fileName { get; set; }
        public string fileLocation { get; set; }
        public bool deletedFlag { get; set; }
    
        public virtual CCClaimPerson CCClaimPerson { get; set; }
        public virtual CCClaim CCClaim { get; set; }
        public virtual CCClient CCClient { get; set; }
    }
}
