//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCClient
    {
        public CCClient()
        {
            this.CCClaimDates = new HashSet<CCClaimDate>();
            this.CCClaimDateTypes = new HashSet<CCClaimDateType>();
            this.CCClaimPersons = new HashSet<CCClaimPerson>();
            this.CCClaims = new HashSet<CCClaim>();
            this.CCClientOrganizations = new HashSet<CCClientOrganization>();
            this.CCCustomLabels = new HashSet<CCCustomLabel>();
            this.CCPersons = new HashSet<CCPerson>();
            this.CCSetting_ClaimDropdownTypes = new HashSet<CCSetting_ClaimDropdownTypes>();
            this.CCSetting_ClaimDropdownValues = new HashSet<CCSetting_ClaimDropdownValues>();
            this.CCSetting_ClaimPersonnelTypes = new HashSet<CCSetting_ClaimPersonnelTypes>();
            this.CCClaimDropdownValues = new HashSet<CCClaimDropdownValue>();
            this.CCClaimTextboxValues = new HashSet<CCClaimTextboxValue>();
            this.CCSetting_ClaimTextboxTypes = new HashSet<CCSetting_ClaimTextboxTypes>();
            this.CCSetting_ClaimCheckboxTypes = new HashSet<CCSetting_ClaimCheckboxTypes>();
            this.CCClaimCheckboxValues = new HashSet<CCClaimCheckboxValue>();
            this.CCSetting_CustomFormSectionSectionItems = new HashSet<CCSetting_CustomFormSectionSectionItems>();
            this.CCSetting_CustomFormSections = new HashSet<CCSetting_CustomFormSections>();
            this.CCClaimMedias = new HashSet<CCClaimMedia>();
        }
    
        public int clientID { get; set; }
        public System.Guid clientGUID { get; set; }
        public string clientName { get; set; }
        public Nullable<int> clientGenericContactCardID { get; set; }
        public string clientTaxID { get; set; }
        public Nullable<int> clientTimeZone { get; set; }
        public string clientNotes { get; set; }
        public string clientDomainName { get; set; }
        public Nullable<bool> clientInactive { get; set; }
        public string clientGroup { get; set; }
    
        public virtual ICollection<CCClaimDate> CCClaimDates { get; set; }
        public virtual ICollection<CCClaimDateType> CCClaimDateTypes { get; set; }
        public virtual ICollection<CCClaimPerson> CCClaimPersons { get; set; }
        public virtual ICollection<CCClaim> CCClaims { get; set; }
        public virtual ICollection<CCClientOrganization> CCClientOrganizations { get; set; }
        public virtual ICollection<CCCustomLabel> CCCustomLabels { get; set; }
        public virtual ICollection<CCPerson> CCPersons { get; set; }
        public virtual ICollection<CCSetting_ClaimDropdownTypes> CCSetting_ClaimDropdownTypes { get; set; }
        public virtual ICollection<CCSetting_ClaimDropdownValues> CCSetting_ClaimDropdownValues { get; set; }
        public virtual ICollection<CCSetting_ClaimPersonnelTypes> CCSetting_ClaimPersonnelTypes { get; set; }
        public virtual ICollection<CCClaimDropdownValue> CCClaimDropdownValues { get; set; }
        public virtual ICollection<CCClaimTextboxValue> CCClaimTextboxValues { get; set; }
        public virtual ICollection<CCSetting_ClaimTextboxTypes> CCSetting_ClaimTextboxTypes { get; set; }
        public virtual ICollection<CCSetting_ClaimCheckboxTypes> CCSetting_ClaimCheckboxTypes { get; set; }
        public virtual ICollection<CCClaimCheckboxValue> CCClaimCheckboxValues { get; set; }
        public virtual ICollection<CCSetting_CustomFormSectionSectionItems> CCSetting_CustomFormSectionSectionItems { get; set; }
        public virtual ICollection<CCSetting_CustomFormSections> CCSetting_CustomFormSections { get; set; }
        public virtual ICollection<CCClaimMedia> CCClaimMedias { get; set; }
    }
}
