//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCClientOrganization
    {
        public int clientOrgID { get; set; }
        public System.Guid clientOrgGUID { get; set; }
        public int clientID { get; set; }
        public int clientOrgTypeID { get; set; }
        public string clientOrgName { get; set; }
        public Nullable<int> clientOrgGenericContactCardID { get; set; }
    
        public virtual CCClient CCClient { get; set; }
    }
}
