//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCClaimDate
    {
        public int claimDateID { get; set; }
        public System.Guid claimGUID { get; set; }
        public int clientID { get; set; }
        public int claimDateTypeID { get; set; }
        public Nullable<System.DateTime> claimDateStamp { get; set; }
    
        public virtual CCClaimDateType CCClaimDateType { get; set; }
        public virtual CCClient CCClient { get; set; }
    }
}
