//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCClaimDateType
    {
        public CCClaimDateType()
        {
            this.CCClaimDates = new HashSet<CCClaimDate>();
        }
    
        public int claimDateTypeID { get; set; }
        public int clientID { get; set; }
        public string claimDateType { get; set; }
        public bool claimDateTypeDisabled { get; set; }
        public bool claimDateTypeDeleted { get; set; }
    
        public virtual ICollection<CCClaimDate> CCClaimDates { get; set; }
        public virtual CCClient CCClient { get; set; }
    }
}
