//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCClaimTextboxValue
    {
        public int recordID { get; set; }
        public int clientID { get; set; }
        public int claimID { get; set; }
        public int textboxTypeID { get; set; }
        public string textboxValue { get; set; }
    
        public virtual CCClaim CCClaim { get; set; }
        public virtual CCClient CCClient { get; set; }
        public virtual CCSetting_ClaimTextboxTypes CCSetting_ClaimTextboxTypes { get; set; }
    }
}
