//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCCustomLabel
    {
        public int labelID { get; set; }
        public int clientID { get; set; }
        public string tableName { get; set; }
        public string columnName { get; set; }
        public string labelText { get; set; }
    
        public virtual CCClient CCClient { get; set; }
    }
}
