//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCGenericContactCard
    {
        public CCGenericContactCard()
        {
            this.CCPersons = new HashSet<CCPerson>();
        }
    
        public int genericContactCardID { get; set; }
        public int clientID { get; set; }
        public int genericContactCardTypeID { get; set; }
        public string genericContactAddrLine1 { get; set; }
        public string genericContactAddrLine2 { get; set; }
        public string genericContactCity { get; set; }
        public string genericContactState { get; set; }
        public string genericContactZIP { get; set; }
        public string genericContactCountry { get; set; }
        public string genericContactPhone1 { get; set; }
        public string genericContactPhone2 { get; set; }
        public string genericContactPhone3 { get; set; }
        public string genericContactPhone4 { get; set; }
        public string genericContactPhone5 { get; set; }
        public string genericContactFax { get; set; }
        public string genericContactEMail1 { get; set; }
        public string genericContactEMail2 { get; set; }
        public string genericContactWebsite { get; set; }
    
        public virtual ICollection<CCPerson> CCPersons { get; set; }
    }
}
