//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCPerson
    {
        public CCPerson()
        {
            this.CCClaimPersons = new HashSet<CCClaimPerson>();
        }
    
        public int personID { get; set; }
        public System.Guid personGUID { get; set; }
        public int clientID { get; set; }
        public string personParentTable { get; set; }
        public Nullable<int> personParentID { get; set; }
        public string personFName { get; set; }
        public string personLName { get; set; }
        public string personMName { get; set; }
        public string personTitle { get; set; }
        public string personSuffix { get; set; }
        public Nullable<int> personGenericContactCardID { get; set; }
        public Nullable<bool> personInactive { get; set; }
        public Nullable<int> personClientOrgID { get; set; }
        public System.DateTime personCreationDate { get; set; }
        public string personUserName { get; set; }
        public string personPassword { get; set; }
        public Nullable<int> personRoleID { get; set; }
    
        public virtual ICollection<CCClaimPerson> CCClaimPersons { get; set; }
        public virtual CCClient CCClient { get; set; }
        public virtual CCGenericContactCard CCGenericContactCard { get; set; }
    }
}
