//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_ClaimDropdownTypes
    {
        public CCSetting_ClaimDropdownTypes()
        {
            this.CCSetting_ClaimDropdownValues = new HashSet<CCSetting_ClaimDropdownValues>();
            this.CCClaimDropdownValues = new HashSet<CCClaimDropdownValue>();
        }
    
        public int dropdownTypeID { get; set; }
        public int clientID { get; set; }
        public string dropdownName { get; set; }
        public bool hideOnNewClaim { get; set; }
        public bool dropdownDisabled { get; set; }
        public bool dropdownDeleted { get; set; }
    
        public virtual CCClient CCClient { get; set; }
        public virtual ICollection<CCSetting_ClaimDropdownValues> CCSetting_ClaimDropdownValues { get; set; }
        public virtual ICollection<CCClaimDropdownValue> CCClaimDropdownValues { get; set; }
    }
}
