//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_CustomFormSectionSectionItems
    {
        public int sectionItemID { get; set; }
        public int clientID { get; set; }
        public int sectionID { get; set; }
        public string elementType { get; set; }
        public int elementTypeID { get; set; }
        public bool elementDisabled { get; set; }
        public bool elementDeleted { get; set; }
    
        public virtual CCClient CCClient { get; set; }
        public virtual CCSetting_CustomFormSections CCSetting_CustomFormSections { get; set; }
    }
}
