//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_ClaimPersonnelTypes
    {
        public CCSetting_ClaimPersonnelTypes()
        {
            this.CCClaimPersons = new HashSet<CCClaimPerson>();
        }
    
        public int claimPersonnelTypeID { get; set; }
        public int clientID { get; set; }
        public string claimPersonnelType { get; set; }
        public bool allowMultiple { get; set; }
        public bool claimPersonnelTypeDisabled { get; set; }
        public bool claimPersonnelTypeDeleted { get; set; }
    
        public virtual ICollection<CCClaimPerson> CCClaimPersons { get; set; }
        public virtual CCClient CCClient { get; set; }
    }
}
