//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_CustomFormSections
    {
        public CCSetting_CustomFormSections()
        {
            this.CCSetting_CustomFormSectionSectionItems = new HashSet<CCSetting_CustomFormSectionSectionItems>();
        }
    
        public int sectionID { get; set; }
        public int clientID { get; set; }
        public int formID { get; set; }
        public string sectionName { get; set; }
        public int sortOrder { get; set; }
    
        public virtual CCClient CCClient { get; set; }
        public virtual ICollection<CCSetting_CustomFormSectionSectionItems> CCSetting_CustomFormSectionSectionItems { get; set; }
        public virtual CCSetting_CustomForms CCSetting_CustomForms { get; set; }
    }
}
