//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_CustomForms
    {
        public CCSetting_CustomForms()
        {
            this.CCSetting_CustomFormSections = new HashSet<CCSetting_CustomFormSections>();
        }
    
        public int formID { get; set; }
        public int clientID { get; set; }
        public string formType { get; set; }
        public string formName { get; set; }
        public string serializedForm { get; set; }
    
        public virtual ICollection<CCSetting_CustomFormSections> CCSetting_CustomFormSections { get; set; }
    }
}
