//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_ClaimDropdownValues
    {
        public CCSetting_ClaimDropdownValues()
        {
            this.CCClaimDropdownValues = new HashSet<CCClaimDropdownValue>();
        }
    
        public int ddValueID { get; set; }
        public int clientID { get; set; }
        public int claimDropdownTypeID { get; set; }
        public string ddValueItem { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public bool itemDisabled { get; set; }
        public bool itemDeleted { get; set; }
    
        public virtual CCClient CCClient { get; set; }
        public virtual CCSetting_ClaimDropdownTypes CCSetting_ClaimDropdownTypes { get; set; }
        public virtual ICollection<CCClaimDropdownValue> CCClaimDropdownValues { get; set; }
    }
}
