//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaims.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting_ClaimCheckboxTypes
    {
        public CCSetting_ClaimCheckboxTypes()
        {
            this.CCClaimCheckboxValues = new HashSet<CCClaimCheckboxValue>();
        }
    
        public int checkboxTypeID { get; set; }
        public int clientID { get; set; }
        public string checkboxName { get; set; }
        public Nullable<bool> checkboxDisabled { get; set; }
        public Nullable<bool> checkboxDeleted { get; set; }
    
        public virtual CCClient CCClient { get; set; }
        public virtual ICollection<CCClaimCheckboxValue> CCClaimCheckboxValues { get; set; }
    }
}
