//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaimsWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CloudClaimsEntities : DbContext
    {
        public CloudClaimsEntities()
            : base("name=CloudClaimsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contactForm> contactForms { get; set; }
        public DbSet<emailSubscription> emailSubscriptions { get; set; }
        public DbSet<IPLog> IPLogs { get; set; }
    
        public virtual int AddIPLog(string iPAddress, string data)
        {
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddIPLog", iPAddressParameter, dataParameter);
        }
    
        public virtual int AddRegistrationRequest(string userLogin, string userPassword, string userFName, string userLName, string userEmail, string userHintQuestion, string userHintAnswer, string iPAddress)
        {
            var userLoginParameter = userLogin != null ?
                new ObjectParameter("userLogin", userLogin) :
                new ObjectParameter("userLogin", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("userPassword", userPassword) :
                new ObjectParameter("userPassword", typeof(string));
    
            var userFNameParameter = userFName != null ?
                new ObjectParameter("userFName", userFName) :
                new ObjectParameter("userFName", typeof(string));
    
            var userLNameParameter = userLName != null ?
                new ObjectParameter("userLName", userLName) :
                new ObjectParameter("userLName", typeof(string));
    
            var userEmailParameter = userEmail != null ?
                new ObjectParameter("userEmail", userEmail) :
                new ObjectParameter("userEmail", typeof(string));
    
            var userHintQuestionParameter = userHintQuestion != null ?
                new ObjectParameter("userHintQuestion", userHintQuestion) :
                new ObjectParameter("userHintQuestion", typeof(string));
    
            var userHintAnswerParameter = userHintAnswer != null ?
                new ObjectParameter("userHintAnswer", userHintAnswer) :
                new ObjectParameter("userHintAnswer", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddRegistrationRequest", userLoginParameter, userPasswordParameter, userFNameParameter, userLNameParameter, userEmailParameter, userHintQuestionParameter, userHintAnswerParameter, iPAddressParameter);
        }
    }
}
