//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaimsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactForm
    {
        public int requestID { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> timeStamp { get; set; }
        public string IPAddress { get; set; }
    }
}
