//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudClaimsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailSubscription
    {
        public int subscriberID { get; set; }
        public string emailAddress { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string IPAddress { get; set; }
    }
}
